### ISSUE TITLE
Issue installing >=0.14.2 on M1 ARM [clang-format]

### ISSUE THREAD

**Issue by baswelsh** [TileDB-Inc/TileDB-Py#1186]
In trying to install the latest version of TileDB-Py on an Apple M1 Macbook Pro running MacOS, the installation repeatedly failed while trying to install dev dependency `clang-format`.  I tried the same installation (under the same python environment) on an older Intel Macbook Pro running MacOS and it installed without issue.

After trying several versions, I found that v0.14.2 was the latest build that I could install on the M1 machine.  Assuming `clang-format` is the issue, could we upgrade this package to the latest in `requirements-dev.txt`? I was able to confirm that the latest build of `clang-format` will install on the M1.

Below is the output from running `pip install tiledb==0.15.6`

```
Collecting tiledb==0.15.6
  Downloading tiledb-0.15.6.tar.gz (283 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.7/283.7 kB 7.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      Collecting black
        Downloading black-22.3.0-py3-none-any.whl (153 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.9/153.9 kB 8.0 MB/s eta 0:00:00
      Collecting cython>=0.27
        Downloading Cython-0.29.30-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl (1.8 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 13.0 MB/s eta 0:00:00
      Collecting cmake<3.22,>=3.21
        Downloading cmake-3.21.4-py2.py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (21.7 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.7/21.7 MB 12.8 MB/s eta 0:00:00
      Collecting clang-format==10.0.1
        Downloading clang-format-10.0.1.tar.gz (8.0 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting numpy>=1.16.5
        Downloading numpy-1.23.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.9 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 13.0 MB/s eta 0:00:00
      Collecting setuptools_scm>=1.5.4
        Downloading setuptools_scm-7.0.2-py3-none-any.whl (40 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 kB 13.4 MB/s eta 0:00:00
      Collecting mypy-extensions>=0.4.3
        Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
      Collecting platformdirs>=2
        Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
      Collecting tomli>=1.1.0
        Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting typing-extensions>=3.10.0.0
        Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
      Collecting pathspec>=0.9.0
        Downloading pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
      Collecting click>=8.0.0
        Downloading click-8.1.3-py3-none-any.whl (96 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 12.1 MB/s eta 0:00:00
      Collecting setuptools
        Using cached setuptools-62.6.0-py3-none-any.whl (1.2 MB)
      Collecting packaging>=20.0
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      Building wheels for collected packages: clang-format
        Building wheel for clang-format (pyproject.toml): started
        Building wheel for clang-format (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for clang-format (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [9 lines of output]
            Traceback (most recent call last):
              File "/tmp/pip-build-env-tgxuyfqc/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
                cmkr = cmaker.CMaker(cmake_executable)
              File "/tmp/pip-build-env-tgxuyfqc/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 141, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)
              File "/tmp/pip-build-env-tgxuyfqc/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
                raise SKBuildError(
      
            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for clang-format
      Failed to build clang-format
      ERROR: Could not build wheels for clang-format, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by nguyenv** [comment]
Thanks for catching this. We are removing the `clang-format` and `black` formatters as build requirements and making them optional dependencies.
