### ISSUE TITLE
intermittent test failure on python3.5

### ISSUE THREAD

**Issue by ihnorton** [TileDB-Inc/TileDB-Py#138]
While testing pypi wheels, I noticed that python3.5 has the following test failure about 1 in every 3 runs. 2.7, 3.6, and 3.7 were all fine on repeated runs.

```
======================================================================
ERROR: test_multiple_attributes (test_libtiledb.DenseArrayTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/tiledb/tests/test_libtiledb.py", line 948, in test_multiple_attributes
    T[:] = V
  File "tiledb/libtiledb.pyx", line 4359, in tiledb.libtiledb.DenseArray.__setitem__
ValueError: mixed C and Fortran array layouts

----------------------------------------------------------------------
```

**Comment by ihnorton** [comment]
Have not seen this in a long time.
