### ISSUE TITLE
Imprecise index bounds error message 

### ISSUE THREAD

**Issue by ihnorton** [TileDB-Inc/TileDB-Py#154]
The last assignment here should have a better error, BoundsError rather than erroring at the TileDB level. (x-ref #102)
```
import numpy as np
import tiledb

dense_array_name = 'test_1d'

ctx = tiledb.Ctx()

dom = tiledb.Domain(tiledb.Dim(ctx=ctx, domain=(0, 11), tile=2, dtype=np.int64), ctx=ctx)
schema = tiledb.ArraySchema(ctx=ctx, domain=dom, sparse=False,
                            attrs=[tiledb.Attr(ctx=ctx, dtype=np.int64)])

tiledb.DenseArray.create(dense_array_name, schema)

with tiledb.DenseArray(dense_array_name, ctx=ctx, mode='w') as A:
    A[:2] = np.arange(2)
    A[3:5] = np.arange(4, 6)
    A[4:6] = np.arange(6, 8)
    A[11:13] = np.arange(8, 10)
#tiledb.consolidate(uri=dense_array_name)
```
->
```
tiledb.libtiledb.TileDBError: [TileDB::Writer] Error: Buffer sizes check failed; Invalid number of cells given for attribute '__attr' (2 != 1)
```

**Comment by ihnorton** [comment]
I guess this is about as good as the numpy error:
```
>>> x[11:13] = 1,2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot copy sequence with size 2 to array axis with dimension 0

cannot copy sequence with size 2 to array axis with dimension 0
```

and arguably better than the odd numpy behavior of only raising an error when multiple items are assigned out of bounds:
```
>>> x[13:15] = 1
>>> x[13:15] = 1,2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot copy sequence with size 2 to array axis with dimension 0

cannot copy sequence with size 2 to array axis with dimension 0
```
