### ISSUE TITLE
Writing to arrays

### ISSUE THREAD

**Issue by aosterthun** [TileDB-Inc/TileDB-Py#176]
When writing data to arrays, the lib does not ensure that the data actually fits into the tiledb.Schema. 

```python
import numpy as np
import sys
import tiledb

# Name of the array to create.
array_name = "writing_sparse_multiple12"


def create_array():
    # The array will be 4x4 with dimensions "rows" and "cols", with domain [1,4].
    dom = tiledb.Domain(tiledb.Dim(name="rows", domain=(1.0, 4.5), tile=2, dtype=np.float64),
                        tiledb.Dim(name="cols", domain=(1.5, 4.4), tile=2, dtype=np.float64))

    # The array will be sparse with a single attribute "a" so each (i,j) cell can store an integer.
    schema = tiledb.ArraySchema(domain=dom, sparse=True,
                                attrs=[tiledb.Attr(name="a", dtype=np.int32)])

    # Create the (empty) array on disk.
    tiledb.SparseArray.create(array_name, schema)


def write_array():
    # Open the array and write to it.
    with tiledb.SparseArray(array_name, mode='w') as A:
        # First write
        I, J = [1, 2, 2], [441, 4, 3]
        data = np.array(([1, 2, 3]))
        A[I, J] = data

        # Second write
        I, J = [4, 2], [1, 4]
        data = np.array(([4, 20]))
        A[I, J] = data


if tiledb.object_type(array_name) != "array":
    create_array()
    write_array()


```

does not create any errors

**Comment by ihnorton** [comment]
Hi @aosterthun, thanks for the report. The current `dev` branch of core TileDB raises the error correctly:

```
~/work/bugs/20190709-py-176-bounds master*
(/cmn/condaenvs/tiledb) ❯ python test.py
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    write_array()
  File "test.py", line 31, in write_array
    A[I, J] = data
  File "tiledb/libtiledb.pyx", line 4738, in tiledb.libtiledb.SparseArray.__setitem__
  File "tiledb/libtiledb.pyx", line 4798, in tiledb.libtiledb.SparseArray._write_sparse
  File "tiledb/libtiledb.pyx", line 254, in tiledb.libtiledb._raise_ctx_err
  File "tiledb/libtiledb.pyx", line 239, in tiledb.libtiledb._raise_tiledb_error
tiledb.libtiledb.TileDBError: [TileDB::Writer] Error: Write failed; Coordinates (1,441) are out of bounds
```

We are finalizing a new release soon, so I will leave this open until confirming it is closed in a release build.

**Comment by ihnorton** [comment]
I confirmed the correct error is raised. Please comment/re-open if needed. Thanks!

```
tiledb                    1.6.0                h4f44bfb_1    conda-forge
tiledb-py                 0.4.3            py37haf112f3_0    conda-forge
