### ISSUE TITLE
Cannot Import tiledb

### ISSUE THREAD

**Issue by imk1** [TileDB-Inc/TileDB-Py#196]
I installed tiledb using pip.  I then opened up a python terminal and ran "import tiledb."  This produced the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/imk1/anaconda2/lib/python2.7/site-packages/tiledb/__init__.py", line 29, in <module>
    from .libtiledb import (
ImportError: cannot import name TileDBError

I also tried to run quickstart_dense.py and got this error:

Traceback (most recent call last):
  File "quickstart_dense.py", line 38, in <module>
    import tiledb
  File "/users/imk1/anaconda2/lib/python2.7/site-packages/tiledb/__init__.py", line 27, in <module>
    ctypes.CDLL(lib_name)
  File "/users/imk1/anaconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtiledb.so: cannot open shared object file: No such file or directory

Do you know what might be causing this and how I might be able to fix it?

I installed tiledb version 0.4.3, my version of openssl is 1.0.2s, and my version of python is 2.7.15.

Thanks so much!

**Comment by imk1** [comment]
Upgrading numpy from version 1.15.4 to version 1.16.4 seems to have solved the problem.
