### ISSUE TITLE
error on call to multi_index where domain not multiple of tile size

### ISSUE THREAD

**Issue by bkmartinjr** [TileDB-Inc/TileDB-Py#231]
Very likely related to #230.   A multi_index call fails unexpectedly:
```
Traceback (most recent call last):
  File "bug.py", line 45, in <module>
    main()
  File "bug.py", line 40, in main
    d = A.multi_index[rows, :]['']
  File "/mnt/c/Users/bruce/projects/tiledb-fun/.venv/lib/python3.6/site-packages/tiledb/multirange_indexing.py", line 120, in __getitem__
    arr.shape = result_shape
ValueError: cannot reshape array of size 516150016 into shape (25000,20646)
```

Extended test case:
```
import tiledb
import numpy as np
import random


def make_array(name, shape):

    filters = tiledb.FilterList([
        tiledb.ZstdFilter(),
    ])
    attrs = [
        tiledb.Attr(dtype=np.float32, filters=filters)
    ]
    domain = tiledb.Domain(tiledb.Dim(name="obs", domain=(0, shape[0] - 1), tile=min(shape[0], 200), dtype=np.uint32),
                           tiledb.Dim(name="var", domain=(0, shape[1] - 1), tile=min(shape[1], 100), dtype=np.uint32))

    schema = tiledb.ArraySchema(domain=domain, sparse=False, attrs=attrs,
                                cell_order='row-major', tile_order='row-major')
    tiledb.DenseArray.create(name, schema)


def main():

    shape = (28000, 20646)
    name = "X"
    make_array(name, shape)

    stride = int(np.power(10, np.around(np.log10(1e8 / shape[1]))))
    with tiledb.DenseArray(name, mode='w') as X:
        for row in range(0, shape[0], stride):
            lim = min(row+stride, shape[0])
            print(row, lim)
            X[row:lim, :] = np.random.rand(lim-row, shape[1])

        tiledb.consolidate(name)

    # Additional code
    rows = random.sample(range(0, shape[0]), k=25_000)
    rows.sort()
    with tiledb.DenseArray(name) as A:
        d = A.multi_index[rows, :]['']
        d.mean(axis=0)


if __name__ == '__main__':
    main()
```

**Comment by ihnorton** [comment]
Hi @bkmartinjr, updated packages with the fix are posted on PyPI and conda. Thanks for the bug report.
