### ISSUE TITLE
likely race condition in DenseArray.__new__

### ISSUE THREAD

**Issue by bkmartinjr** [TileDB-Inc/TileDB-Py#244]
Test program below exposes (what I believe is a) race in class handling in DenseArray.  The test program is completely artificial - it just spins up 5 threads, each of which open an S3 object and ask its shape.   Without a sleep to sequence their execution, it fails inside the DenseArray.__new__ method.

Run with the sleep statement in worker(), I see:
```
python cctest.py
starting... 0
starting... 1
working... 0
ending... 0 (1305994, 972)
starting... 2
working... 1
ending... 1 (1305994, 972)
starting... 3
working... 2
ending... 2 (1305994, 972)
starting... 4
working... 3
ending... 3 (1305994, 972)
working... 4
ending... 4 (1305994, 972)
all done [(1305994, 972), (1305994, 972), (1305994, 972), (1305994, 972), (1305994, 972)]
```

Run with the sleep in worker removed/commented out:
```
$ python cctest.py
starting... 0
starting... 1
starting... 2
working... 0
ending... 0 (1305994, 972)
starting... 3
working... 2
ending... 2 (1305994, 972)
starting... 4
working... 3
ending... 3 (1305994, 972)
working... 4
ending... 4 (1305994, 972)
Traceback (most recent call last):
  File "cctest.py", line 33, in <module>
    main()
  File "cctest.py", line 27, in main
    res = [f.result() for f in concurrent.futures.as_completed(futures)]
  File "cctest.py", line 27, in <listcomp>
    res = [f.result() for f in concurrent.futures.as_completed(futures)]
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "cctest.py", line 11, in worker
    with tiledb.DenseArray(uri) as A:
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/tiledb/array.py", line 10, in __new__
    DenseArray.__bases__ = DenseArray.__bases__ + (cloudarray.CloudArray,)
TypeError: duplicate base class CloudArray
```

Test case:
```
import tiledb
import time
import numpy as np
import concurrent.futures


def worker(n, uri):
    print('starting...', n)
    # time.sleep(n)

    with tiledb.DenseArray(uri) as A:
        print('working...', n)
        res = A.shape

    print('ending...', n, res)
    return res


def main():
    executor_cls = concurrent.futures.ThreadPoolExecutor

    uri = "s3://tiledb-eval/10x_mouse_13MM_processed-Xr3zstd.cxg/X"

    with executor_cls(max_workers=2) as executor:
        futures = [executor.submit(worker, n, uri) for n in range(0, 5)]
        res = [f.result() for f in concurrent.futures.as_completed(futures)]

    print('all done', res)


if __name__ == '__main__':
    main()
```

**Comment by ihnorton** [comment]
This is probably https://bugs.python.org/issue38884 -- apparently `import` is not thread-safe, despite both the GIL and the import lock. Will work around.
