### ISSUE TITLE
np.datetime64 SparseArray read error - TypeError: .. argument must not be 'datetime.datetime'

### ISSUE THREAD

**Issue by outdoorpet** [TileDB-Inc/TileDB-Py#260]
Hi,
I have written some code to test the error that I am receiving. 

It seems to occur when the precision in my code is set to less than "ns" (i.e. "us", "ms" etc...). It doesn't seem to matter what the sampling interval is set to. I don't think there is a problem with my code?

Error when:
`sampling_interval = np.timedelta64(1, "s")` & `precision = np.timedelta64(1, "ms")`

```
Traceback (most recent call last):
  File "........./tiledb_datetime_test.py", line 80, in <module>
    vals = T[data_start_time: data_end_time]
  File "tiledb/libtiledb.pyx", line 4479, in tiledb.libtiledb.SparseArrayImpl.__getitem__
  File "tiledb/libtiledb.pyx", line 4589, in tiledb.libtiledb.SparseArrayImpl.subarray
  File "tiledb/libtiledb.pyx", line 4598, in genexpr
  File "tiledb/libtiledb.pyx", line 4598, in genexpr
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'
```

```
import random
import numpy as np
import tiledb
import os
import shutil
import re

# ====================== User input required ======================

array_name = "tiledb_datetime_test"

num_samples_range = [1, 10]

sampling_interval = np.timedelta64(2, "m")

precision = np.timedelta64(1, "ns")

data_dtype = np.dtype("int32")

# =================================================================

if not sampling_interval >= precision:
    raise ValueError("Sampling Interval must be greater than Precision")

if os.path.isdir(array_name):
    print("Removing old data")
    shutil.rmtree(array_name)


def precision_character_from_dtype(dtype):
    m = re.search(r"\[(\w+)\]", str(dtype))
    if not m is None:
        return m.group(1)


# get character code for the precision
precision_character = precision_character_from_dtype(precision.dtype)

# first generate data to put into the tiledb array
data_start_time = np.array([2**5], dtype=np.dtype("datetime64[{}]".format(precision_character)))[0]

num_samples = random.randint(num_samples_range[0], num_samples_range[1])

data_unit_array = (np.random.rand(num_samples)*1000).astype(data_dtype)

data_end_time = data_start_time + ((data_unit_array.size - 1) * sampling_interval)

sample_time_array = np.arange(
    data_start_time, data_end_time + sampling_interval,
    step=sampling_interval)

# now make the domain, tile and data type at the specified precision
array_domain = (np.array([0], dtype=np.dtype("datetime64[{}]".format(precision_character)))[0],
                np.array([(2 ** 63)-1], dtype=np.dtype("datetime64[{}]".format(precision_character)))[0])

array_tile = sampling_interval.astype(precision.dtype)

array_dtype = np.dtype("datetime64[{}]".format(precision_character))

dim = tiledb.Dim(name='sample_time', domain=array_domain,
                 tile=array_tile,
                 dtype=array_dtype)

dom = tiledb.Domain(dim)
schema = tiledb.ArraySchema(domain=dom, sparse=True, attrs=(tiledb.Attr('data', dtype=data_dtype),))

tiledb.Array.create(array_name, schema)

with tiledb.SparseArray(array_name, 'w') as T:
    T[sample_time_array] = {'data': data_unit_array}

# read the previously written data to validate
with tiledb.SparseArray(array_name, 'r', attr='data') as T:
    vals = T[data_start_time: data_end_time]

print(vals)
```

**Comment by eddelbuettel** [comment]
Hm, works for me, just copying your file and running it:

```sh
edd@rob:~/git/tiledb-adhoc/python(master)$ python3 issue260.py 
OrderedDict([('coords', array([('1970-01-01T00:00:00.000000032',),
       ('1970-01-01T00:02:00.000000032',),
       ('1970-01-01T00:04:00.000000032',),
       ('1970-01-01T00:06:00.000000032',),
       ('1970-01-01T00:08:00.000000032',),
       ('1970-01-01T00:10:00.000000032',),
       ('1970-01-01T00:12:00.000000032',),
       ('1970-01-01T00:14:00.000000032',),
       ('1970-01-01T00:16:00.000000032',)],
      dtype=[('sample_time', '<M8[ns]')])), ('data', array([596, 934, 366, 502, 551, 866, 623, 898, 596], dtype=int32))])
edd@rob:~/git/tiledb-adhoc/python(master)$ python3 issue260.py 
Removing old data
OrderedDict([('coords', array([('1970-01-01T00:00:00.000000032',),
       ('1970-01-01T00:02:00.000000032',),
       ('1970-01-01T00:04:00.000000032',),
       ('1970-01-01T00:06:00.000000032',),
       ('1970-01-01T00:08:00.000000032',),
       ('1970-01-01T00:10:00.000000032',),
       ('1970-01-01T00:12:00.000000032',),
       ('1970-01-01T00:14:00.000000032',),
       ('1970-01-01T00:16:00.000000032',),
       ('1970-01-01T00:18:00.000000032',)],
      dtype=[('sample_time', '<M8[ns]')])), ('data', array([848, 497, 531, 417, 178, 873, 436, 720, 236, 148], dtype=int32))])
edd@rob:~/git/tiledb-adhoc/python(master)$ 
```

**Comment by outdoorpet** [comment]
Sorry the parameters in the supplied code work. 

Could you try using `precision = np.timedelta64(1, "ms")`

**Comment by eddelbuettel** [comment]
My bad and just noticed that myself.  With

```py
sampling_interval = np.timedelta64(1, "m")          

precision = np.timedelta64(1, "ms")
```

it errors as you said so please disregard my earlier comment which I'll remove -- I had not read carefully enough.

**Comment by ihnorton** [comment]
Thanks for the excellent bug report, @outdoorpet.

**Comment by outdoorpet** [comment]
Thanks for the quick fix! I will keep an eye out for a release

**Comment by ihnorton** [comment]
@outdoorpet there's a new release (0.5.6) up on pypi and conda with the fix above.
