### ISSUE TITLE
Error install TileDB on conda

### ISSUE THREAD

**Issue by Donaldpherman** [TileDB-Inc/TileDB-Py#302]
any ideas on how to fix this issue and get TileDB to install.

```
(base) C:\WINDOWS\system32>conda install -c conda-forge tiledb-py
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining entrypoints:   4%|███████▌                                                                                                                                                                       | 13/302 [00:19<06:18,  1.31s/it]/Examining ca-certificates:   8%|██████████████▏                                                                                                                                                            | 25/302 [01:55<31:20,  6.79s/it]\Examining pytest-astropy-header:   9%|███████████████▎                                                                                                                                                     | 28/302 [01:57<17:01,  3.73s/it]-Examining wcwidth:  11%|███████████████████▌                                                                                                                                                               | 33/302 [02:07<12:47,  2.85s/it]|Examining ipykernel:  13%|███████████████████████▍                                                                                                                                                         | 40/302 [02:13<07:41,  1.76s/it]-Examining tornado:  16%|███████████████████████████▊                                                                                                                                                       | 47/302 [02:29<07:23,  1.74s/it]|Examining autopep8:  16%|███████████████████████████▋                                                                                                                                                      | 47/302 [02:30<07:23,  1.74s/it]/Examining nose:  19%|██████████████████████████████████▎                                                                                                                                                   | 57/302 [02:55<10:28,  2.57s/it]/Examining python-libarchive-c:  21%|██████████████████████████████████▊                                                                                                                                    | 63/302 [03:48<02:41,  1.48it/s]/Examining pandas:  32%|█████████████████████████████████████████████████████████▊                                                                                                                          | 97/302 [04:52<02:01,  1.68it/s]|Examining jsonschema:  34%|███████████████████████████████████████████████████████████                                                                                                                    | 102/302 [05:03<05:53,  1.77s/it]\Examining bitarray:  35%|█████████████████████████████████████████████████████████████▌                                                                                                                   | 105/302 [05:07<04:56,  1.50s/it]/Examining distributed:  37%|████████████████████████████████████████████████████████████████▌                                                                                                             | 112/302 [05:50<19:05,  6.03s/it]\Examining sphinxcontrib-qthelp:  39%|█████████████████████████████████████████████████████████████████                                                                                                    | 119/302 [06:29<21:00,  6.89s/it]|Examining hypothesis:  41%|████████████████████████████████████████████████████████████████████████▍                                                                                                      | 125/302 [06:42<07:10,  2.43s/it]|Examining snowballstemmer:  44%|██████████████████████████████████████████████████████████████████████████▎                                                                                               | 132/302 [07:08<04:18,  1.52s/it]-Examining wheel:  47%|█████████████████████████████████████████████████████████████████████████████████████▏                                                                                              | 143/302 [07:13<01:25,  1.85it/s]/Examining cytoolz:  49%|███████████████████████████████████████████████████████████████████████████████████████▏                                                                                          | 148/302 [07:23<03:29,  1.36s/it]|Examining jupyter_client:  54%|███████████████████████████████████████████████████████████████████████████████████████████▋                                                                               | 162/302 [07:34<02:45,  1.18s/it]|Examining libxslt:  56%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                             | 170/302 [07:43<01:46,  1.24it/s]|Examining zict:  65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                               | 197/302 [08:19<00:26,  4.01it/s]-Examining json5:  73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                 | 219/302 [09:13<01:06,  1.25it/s]-Examining anaconda-navigator:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 261/302 [10:01<00:20,  1.98it/s]\Examining ujson:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 293/302 [10:53<00:09,  1.06s/it]-Examining pluggy:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 300/302 [10:57<00:01,  1.32it/s]-Examining conflict for anaconda-project matplotlib matplotlib-base distributed seaborn dask anaconda jupyter_client notebook spyder-kernels qtconsole pandas anaconda-client python-dateutil scikit-image bkcharts nbconvert jupyter_console/Examining conflict for ipython importlib_metadata pickleshare testpath conda-build pytest pathlib2:  12%|████████████                                                                                      | 37/302 [13:27<42:45,  9.68s/it]\Examining conflict for anaconda ipython ipykernel jupyter ipywidgets h5py pyreadline jupyter_console:  14%|█████████████                                                                                   | 41/302 [14:09<36:57,  8.50s/it]/Examining conflict for jupyter_core anaconda ipython jupyter_client notebook nbconvert ipython_genutils qtconsole ipykernel jupyter ipywidgets anaconda-client spyder widgetsnbextension traitlets nbformat jupyterlab jupyterlab_server:  1/Examining conflict for numpy scipy blas:  20%|██████████████████████████████▉                                                                                                                          | 61/302 [6:46:34<2:11:19, 32.69s/it]\Examining conflict for libarchive matplotlib pytables imageio matplotlib-base zstd tiledb-py lxml qt seaborn libcurl python-libarchive-c anaconda libxml2 libpng libtiff zlib conda-build scikit-image libxslt freetype blosc pyqt libssh2 h/Examining conflict for tk libcurl anaconda anaconda-navigator curl imageio pillow scikit-image krb5 bokeh:  29%|█████████████████████████▋                                                              | 88/302 [14:27:12<53:09, 14.90s/it]-Examining conflict for anaconda astroid pylint:  39%|█████████████████████████████████████████████████████████                                                                                         | 118/302 [14:32:16<29:05,  9.49s/it]\Examining conflict for matplotlib anaconda anaconda-navigator qtconsole spyder pyqt sip navigator-updater:  42%|████████████████████████████████████▊                                                  | 128/302 [14:33:27<20:54,  7.21s/it]/Examining conflict for anaconda dask spyder-kernels spyder distributed scikit-image cloudpickle:  43%|██████████████████████████████████████████                                                       | 131/302 [14:33:59<28:00,  9.83s/it]|Examining conflict for tqdm anaconda conda conda-build conda-verify conda-package-handling:  44%|████████████████████████████████████████████▉                                                         | 133/302 [14:34:31<34:58, 12.42s/it]/Examining conflict for anaconda atomicwrites pytest-astropy-header pytest-astropy pytest-remotedata spyder pytest astropy pytest-openfiles pytest-doctestplus pytest-arraydiff:  57%|██████████▏       | 171/302 [14:39:27<26:38, 12.21s/it]\Examining conflict for scikit-learn nltk anaconda:  61%|███████████████████████████████████████████████████████████████████████████████████████▌                                                       | 185/302 [14:41:38<19:26,  9.97s/it]\Examining conflict for anaconda bcrypt pip python wheel:  66%|██████████████████████████████████████████████████████████████████████████████████████████▎                                              | 199/302 [14:44:02<17:41, 10.31s/it]/Examining conflict for scikit-image anaconda distributed dask:  72%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 218/302 [14:46:33<13:13,  9.45s/it]/Examining conflict for anaconda distributed dask zict:  73%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 220/302 [14:47:05<17:37, 12.89s/it]/Examining conflict for anaconda dask distributed bokeh bkcharts:  74%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                 | 224/302 [14:48:20<18:53, 14.53s/it]\Examining conflict for distributed dask bokeh:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 227/302 [14:49:09<20:10, 16.14s/it]/Examining conflict for _ipyw_jlab_nb_ext_conf anaconda jupyter ipywidgets:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 288/302 [14:58:24<02:18,  9.86s/it]-Examining conflict for anaconda importlib_metadata path path.py pytest pluggy jsonschema keyring zipp:  98%|█████████████████████████████████████████████████████████████████████████████████████████▏ | 296/302 [14:59:31<00:57,  9.66s/it]-Examining conflict for scikit-image anaconda pywavelets: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 301/302 [15:00:31<00:09,  9.62s/it]\failed                                                      \                                                                                                                                                                             |

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\tools\Anaconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "C:\tools\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\tools\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\tools\Anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "C:\tools\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\tools\Anaconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "C:\tools\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\tools\Anaconda3\lib\site-packages\conda\resolve.py", line 1316, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError:
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.

    conda config --set unsatisfiable_hints True


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\tools\Anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\tools\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\tools\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\tools\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\tools\Anaconda3\lib\site-packages\conda\cli\install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "C:\tools\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\tools\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\tools\Anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "C:\tools\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\tools\Anaconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "C:\tools\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\tools\Anaconda3\lib\site-packages\conda\resolve.py", line 1318, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "C:\tools\Anaconda3\lib\site-packages\conda\resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "C:\tools\Anaconda3\lib\site-packages\conda\resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "C:\tools\Anaconda3\lib\site-packages\conda\resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "C:\tools\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "C:\tools\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\tools\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\tools\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "C:\tools\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ C:\tools\Anaconda3\Scripts\conda-script.py install -c conda-forge tiledb-py`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\tools\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\tools\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\tools\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\tools\Anaconda3\python.exe
               CONDA_ROOT=C:\tools\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\donal
                     PATH=C:\tools\Anaconda3;C:\tools\Anaconda3\Library\mingw-w64\bin;C:\tools\A
                          naconda3\Library\usr\bin;C:\tools\Anaconda3\Library\bin;C:\tools\Anaco
                          nda3\Scripts;C:\tools\Anaconda3\bin;C:\tools\Anaconda3;C:\tools\Anacon
                          da3\Library\mingw-w64\bin;C:\tools\Anaconda3\Library\usr\bin;C:\tools\
                          Anaconda3\Library\bin;C:\tools\Anaconda3\Scripts;C:\tools\Anaconda3\bi
                          n;C:\tools\Anaconda3\condabin;C:\Python38\Scripts;C:\Python38;C:\Users
                          \donal\source\Libraries\depot_tools;C:\ProgramData\chocolatey\bin;C:\W
                          indows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System3
                          2\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program
                          Files\dotnet;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn;C:\Program Files\LLVM\bin;C:\WINDOWS\system32;C:
                          \WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShel
                          l\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program
                          Files\Git\cmd;C:\Users\donal\AppData\Roaming\npm;C:\Program
                          Files\nodejs;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\lib\
                          mingw\tools\install\mingw64\bin;C:\Users\donal\AppData\Local\Programs\
                          Microsoft VS Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\tools\Anaconda3
            shell level : 1
       user config file : C:\Users\donal\.condarc
 populated config files : C:\Users\donal\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.1
       base environment : C:\tools\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\tools\Anaconda3\pkgs
                          C:\Users\donal\.conda\pkgs
                          C:\Users\donal\AppData\Local\conda\conda\pkgs
       envs directories : C:\tools\Anaconda3\envs
                          C:\Users\donal\.conda\envs
                          C:\Users\donal\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true



(base) C:\WINDOWS\system32>
```

**Comment by ihnorton** [comment]
@Donaldpherman I'm not sure what to make of that error, it looks like a conda bug. Unfortunately, mixing older environments with new packages can sometimes cause problems. However, I now have a wheel build system for Windows wheels, so I will do a little bit of testing and then upload them on PyPI (will comment on the other issue).
