### ISSUE TITLE
Test errors on linux32

### ISSUE THREAD

**Issue by gsakkis** [TileDB-Inc/TileDB-Py#381]
I'm getting the following errors when running the test suite on a local linux32 build:
```
======================================================================
ERROR: test_docs (test_examples.ExamplesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gsk/projects/ESA/TileDB-Py/tiledb/tests/test_examples.py", line 36, in test_docs
    run_checked(doctest_args)
  File "/home/gsk/projects/ESA/TileDB-Py/tiledb/tests/test_examples.py", line 17, in run_checked
    sys.exit(1)
SystemExit: 1

======================================================================
FAIL: test_open_with_timestamp (test_libtiledb.DenseArrayTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gsk/projects/ESA/TileDB-Py/tiledb/tests/test_libtiledb.py", line 1057, in test_open_with_timestamp
    self.assertEqual(T[0], 0)
AssertionError: array(1.) != 0

======================================================================
FAIL: test_metadata_consecutive (test_metadata.MetadataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gsk/projects/ESA/TileDB-Py/tiledb/tests/test_metadata.py", line 154, in test_metadata_consecutive
    self.assertEqual(A.meta['randint'], randints[-1])
AssertionError: 7091542844296747781 != 278972771066685295

======================================================================
FAIL: test_multirange_1d_sparse_double (test_multi_index.TestMultiRange)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gsk/projects/ESA/TileDB-Py/tiledb/tests/test_multi_index.py", line 351, in test_multirange_1d_sparse_double
    A.multi_index[ [0] ][attr_name]
  File "/home/gsk/projects/ESA/TileDB-Py/.eggs/numpy-1.19.1-py3.6-linux-i686.egg/numpy/testing/_private/utils.py", line 931, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/gsk/projects/ESA/TileDB-Py/.eggs/numpy-1.19.1-py3.6-linux-i686.egg/numpy/testing/_private/utils.py", line 759, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(shapes (1,), (0,) mismatch)
 x: array([0.860108])
 y: array([], dtype=float64)

----------------------------------------------------------------------
Ran 167 tests in 24.034s
```

The first one in `test_docs` is expected (it prints `array([0, 0, 0, 0, 0], dtype=int64)` instead of `array([0, 0, 0, 0, 0])` expected on 64bit system) but the next three need closer inspection.

**Comment by ihnorton** [comment]
https://app.shortcut.com/tiledb-inc/story/40418/backlog-support-linux32
