### ISSUE TITLE
Impossibile to install using pip on Apple Silicon

### ISSUE THREAD

**Issue by lucalianas** [TileDB-Inc/TileDB-Py#710]
Hi, I can't install TileDB using pip when running Python3.9 version compiled for Apple Silicon hardware (Python3.9 was installed using Homebrew)

This is the output I get from pip

```
❯ pip install tiledb
Collecting tiledb
  Using cached tiledb-0.10.2.tar.gz (232 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting numpy>=1.16.5
  Using cached numpy-1.21.2-cp38-cp38-macosx_11_0_arm64.whl (12.3 MB)
Building wheels for collected packages: tiledb
  Building wheel for tiledb (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/luca/work/python_env/promort_tools/bin/python /Users/luca/work/python_env/promort_tools/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/23/q0syrgm57qgfffdmdh6mnffw0000gn/T/tmpf_vbra8q
       cwd: /private/var/folders/23/q0syrgm57qgfffdmdh6mnffw0000gn/T/pip-install-gmstgq04/tiledb_8c853fe44b4141e88dff3b4b536c80a0
  Complete output (23 lines):
  TILEDB_PATH from env: ''
  Traceback (most recent call last):
    File "/Users/luca/work/python_env/promort_tools/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/Users/luca/work/python_env/promort_tools/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/luca/work/python_env/promort_tools/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/23/q0syrgm57qgfffdmdh6mnffw0000gn/T/pip-build-env-bti5b7wd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/23/q0syrgm57qgfffdmdh6mnffw0000gn/T/pip-build-env-bti5b7wd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/23/q0syrgm57qgfffdmdh6mnffw0000gn/T/pip-build-env-bti5b7wd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/23/q0syrgm57qgfffdmdh6mnffw0000gn/T/pip-build-env-bti5b7wd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 718, in <module>
      setup_requires=setup_requires(),
    File "setup.py", line 509, in setup_requires
      req = parse_requirements("misc/requirements_wheel.txt")
    File "setup.py", line 500, in parse_requirements
      with open(req_file) as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'misc/requirements_wheel.txt'
  ----------------------------------------
  ERROR: Failed building wheel for tiledb
Failed to build tiledb
ERROR: Could not build wheels for tiledb which use PEP 517 and cannot be installed directly
```

**Comment by ihnorton** [comment]
Hi @lucalianas, this issue should be fixed in TileDB-Py 0.10.4 -- `pip install tiledb --no-binary tiledb` again works as expected on linux/x86_64. However, I'm not able to test the build on macOS arm64 right now, so it _may_ also be necessary to separately install openssl (eg with homebrew). Please let us know if this is not resolved, or of any further issues here, and we'll be happy to reopen.

**Comment by lucalianas** [comment]
Hi @ihnorton I was able to install tiledb 0.10.4 using pip on python 3.9 (installed using homebrew) running on macOS arm64

**Comment by ihnorton** [comment]
That's great, thanks for updating! Please let us know of any further issues.

**Comment by ihnorton** [comment]
For future reference, we now provide [wheels for macOS arm64](https://pypi.org/project/tiledb/0.24.0/#files), so building from source should usually not be necessary (the most common reason for errors is missing tools, see [install from source](https://docs.tiledb.com/main/how-to/installation/building-from-source/python) instructions)
