### ISSUE TITLE
.query().df[:] fails on empty array

### ISSUE THREAD

**Issue by bkmartinjr** [TileDB-Inc/TileDB-Py#716]
This unexpectedly fails when the array is empty, using tiledb version `0.10.2`:
```
with tiledb.open(uri, "r") as A:
    print(A.query().df[:])
```

output:
```
Traceback (most recent call last):
  File "/home/bruce/projects/aurora/test/bug1.py", line 49, in <module>
    print(A.query().df[:])
  File "/home/bruce/projects/aurora/venv/lib/python3.9/site-packages/tiledb/multirange_indexing.py", line 295, in __getitem__
    result = self._run_query(query, preload_metadata=True)
  File "/home/bruce/projects/aurora/venv/lib/python3.9/site-packages/tiledb/multirange_indexing.py", line 217, in _run_query
    table = self.pyquery._buffers_to_pa_table()
  File "pyarrow/array.pxi", line 1308, in pyarrow.lib.Array._import_from_c
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Expected 3 buffers for imported type large_string, ArrowArray struct has 2
```

test case:
```
import numpy as np
import tiledb


def create_array(uri):

    keys = ["a", "b"]
    iiu32 = np.iinfo(np.uint32)
    uint32_domain = (iiu32.min, iiu32.max - 1)
    tiledb.Array.create(
        uri,
        tiledb.ArraySchema(
            domain=tiledb.Domain(
                tiledb.Dim(
                    name="var",
                    domain=uint32_domain,
                    tile=2048,
                    dtype=np.uint32,
                ),
            ),
            sparse=True,
            allows_duplicates=False,
            attrs=[tiledb.Attr(name=key, dtype="ascii", var=True) for key in keys],
            cell_order="row-major",
            tile_order="row-major",
            capacity=10000,
        ),
    )


uri = "test_query"
create_array(uri)

with tiledb.open(uri, "r") as A:  # works
    print("Test 1")
    print(A[:])

with tiledb.open(uri, "r") as A:  # fails
    print("Test 2")
    print(A.query().df[:])
```

**Comment by ihnorton** [comment]
This is fixed in TileDB-Py 0.10.3, please bump if needed and we will reopen.
